baseurl = "/"
title = "物数科技"
theme = "hugo-universal-theme"
languageCode = "zh_CN"
#多语言情况下i18n的设置，字符串与i18n中语言文件名保持一致
defaultContentLanguage = "zh"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
googleAnalytics = ""
# 新闻每页的数量
paginate = 10
# weight 表示菜单的顺序
[menu]
[[menu.main]]
    name = "主页"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "热点新闻"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "我们的业务"
    identifier = "business"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "关于我们"
    weight = 4

[[menu.main]]
    name = "区块链学习"
    url  = "/test/"
    weight = 5

[[menu.main]]
    parent="about"
    name = "公司介绍"
    url  = "/test/"
    weight = 6

[[menu.main]]
    parent="business"
    identifier="products"
    name = "产品介绍"
    url  = "/test/"
    weight = 31

[[menu.main]]
    parent="business"
    identifier="solution"
    name = "应用方案"
    weight = 32

[[menu.main]]
    parent="solution"
    identifier="spc-finance"
    url  = "/spc-finance/"
    name = "供应链金融和供应链优化"
    weight = 321

[[menu.main]]
    parent="solution"
    identifier="provenance"
    url  = "/provenance/"
    name = "溯源"
    weight = 322
[[menu.main]]
    parent="solution"
    identifier="regtech"
    url  = "/regtech/"
    name = "监管科技"
    weight = 323
[[menu.main]]
    parent="solution"
    identifier="iot"
    url  = "/iot/"
    name = "工业互联网"
    weight = 324

[[menu.main]]
    parent="about"
    identifier="team"
    url  = "/team/"
    name = "我们的团队"
    weight = 10
[[menu.main]]
    parent="about"
    identifier="joinus"
    url  = "/joinus/"
    name = "加入我们"
    weight = 11
# Topbar的超链接

[[menu.topbar]]
    weight = 1
    name = "English"
    url = "/en"

[params]
    viewMorePostLink = "/blog/"
    author = "张伟"
    defaultKeywords = ["区块链", "物数", "科技"]
    defaultDescription = "物数科技官方网站"
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"
    email = "kanseefoil@gmail.com"
    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright © WUSHU 2018-2019. All Rights Reserved. 沪ICP备18023735号-2"
    date_format = "Jan 2, 2006"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>物数（上海）信息科技有限公司</strong>
        <br>上海市浦东新区龙阳路2277号11楼1101室 
        <br>
        <strong></strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Tel: +021 xxxx xxxx or zhumin@umarkcloud.cn</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.features]
    enable = true

[params.aboutlist]
    enable = true
    title = "关于我们"

[params.clients]
    enable = true
    title = "我们的客户"

[params.recent_posts]
    enable = true
    title = "新闻动态"